# reference: https://detekt.github.io/detekt/comments.html

complexity:
  TooManyFunctions:
    ignorePrivate: true
    thresholdInClasses: 13
  ComplexMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

style:
  UtilityClassWithPublicConstructor:
    active: false
  MagicNumber:
    active: false
    ignoreAnnotation: true
    ignoreNumbers: ['-1', '0', '1', '2', '3', '5', '6', '24', '31', '60', '1000', '3600000', '86400']
  ThrowsCount:
    max: 4
  ForbiddenComment:
    active: false
    values: ['TODO:', 'FIXME:', 'STOPSHIP:']
    allowedPatterns: ''
  ProtectedMemberInFinalClass:
    active: false
  ReturnCount:
    active: false
  UnusedPrivateMember:
    active: false
  FunctionOnlyReturningConstant:
    active: false

formatting:
  NoWildcardImports:
    active: false
    excludeImports:
      - 'java.util.*'

naming:
  MatchingDeclarationName:
    active: false

performance:
  SpreadOperator:
    active: false